post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
end


platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps', '8.4.0'
  pod 'GooglePlaces', '7.1.0'
  pod 'GoogleUserMessagingPlatform'
  pod 'ToastSwiftUI'
  pod 'NodleSDK', :git => 'https://github.com/NodleCode/NodleSDK-Release', :branch => 'main', :tag => '0.0.21'
  pod 'SQLite.swift', '~> 0.13.3'
  pod 'SwiftCBOR', '~> 0.4.5'
  pod 'SwiftProtobuf', '~> 1.19.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftLint'

end