[versions]
max-keppeler = "1.3.0"

[libraries]
datePickerCore = { module = "com.maxkeppeler.sheets-compose-dialogs:core", version.ref = "max-keppeler" }
datePickerCalendar = { module = "com.maxkeppeler.sheets-compose-dialogs:calendar", version.ref = "max-keppeler" }
