[versions]
retrofit = "2.9.0"

[libraries]
retrofitMain = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
