[versions]
sqlDelight = "2.0.2"

[libraries]
sqlCommon = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlIos = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlAndroid = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlJKvm = { module = "app.cash.sqldelight:jdbc-driver", version.ref = "sqlDelight" }
sqlCoroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }

[plugins]
sqldelight = { id = "app.cash.sqldelight" , version.ref = "sqlDelight" }