[versions]
firebase-kmp = "1.10.4"
firebase-android = "33.9.0"
firebase-android-messaging = "24.1.0"

[libraries]
firebaseAuthentication = { module = "dev.gitlive:firebase-auth", version.ref = "firebase-kmp" }
firebaseFirestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase-kmp" }
firebaseStorage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase-kmp" }
androidFirebase = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-android" }
androidFirebaseKTXStorage = { module = "com.google.firebase:firebase-storage-ktx" }
androidFirebaseAnalytics = { module = "com.google.firebase:firebase-analytics" }
androidFirebaseMessaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-android-messaging" }
androidFirebaseMessagingKTX = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebase-android-messaging" }
