[versions]
material-design-3 = "1.2.1"

[libraries]
material-design-3 = { module = "androidx.compose.material3:material3", version.ref = "material-design-3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material-design-3" }
