[versions]
ktor = "2.3.3"

[libraries]
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorAndroid = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorIos = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
