[versions]
review = "2.0.2"
map = "6.4.4"
play-service = "19.0.0"
google-places = "4.1.0"
google-service = "4.4.2"
guava = "33.4.0-jre"
ads = "23.6.0"
auth = "21.3.0"

[libraries]
reviewMain = { module = "com.google.android.play:review", version.ref = "review" }
reviewKtx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
composeMap = { module = "com.google.maps.android:maps-compose", version.ref = "map" }
gmsGoogleMap = { module = "com.google.android.gms:play-services-maps", version.ref = "play-service" }
googlePlaces = { module = "com.google.android.libraries.places:places", version.ref = "google-places" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
playAdsService = { module = "com.google.android.gms:play-services-ads", version.ref = "ads" }
auth = { module = "com.google.android.gms:play-services-auth", version.ref = "auth" }

[plugins]
googleServices = { id = "com.google.gms.google-services", version.ref = "google-service" }
mapsSecrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }