[versions]
koin = "3.3.2"
koin-android-compose = "3.4.1"

[libraries]
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinAndroidxCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android-compose" }
