[versions]
sqldelight = "2.0.2"

[libraries]
sqlCommon = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqlDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqlIos = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqlAndroid = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqlJKvm = { module = "app.cash.sqldelight:jdbc-driver", version.ref = "sqldelight" }

[plugins]
initiliazer = { id = "app.cash.sqldelight", version.ref = "sqldelight" }