name: Android CI
on: pull_request

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make empty local.properties file
        run: touch KMP-Idea/local.properties

      - name: Test Android App
        working-directory: KMP-Idea
        run: ./gradlew :androidApp:test
